services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" 
    networks:
      - mern_network
    

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  
    networks:
      - mern_network
    
networks:
  mern_network:
    driver: bridge 
